Algoritmo "idade de Creuza"
//  
//  

Var
   I: inteiro
   N: inteiro
   A: inteiro



Inicio
      escreva("Em que ano estamos ? ")
                  Leia(A)
      escreval ("Em que ano Creuza nasceu ? ")
               Leia(N)
               I <- A - N
      escreva("Creuza tem", I ," anos,")
      se (I >= 18) entao
         escreva(" então Creuza já é de maior.")
      FimSe



Fimalgoritmo