Algoritmo "quantos dolares Creuza tem?"

Var
   R: real
   D: real

Inicio
      escreval ("Olá, eu sou Creuza tenho xxx reais e vou para os Estados unidos. Quanto esse dinheiro, em reais, da em dólares?")
      escreva ("Quantos reais Creuza tem ? ")
      Leia (R)
      D <- (R / 5.44)
      escreval("Convertendo esse valor para dólares, Creuza terá, aproximadamente,", D , " dólares.")
      escreva("Muito obrigado ! Agora posso ir pros Estados Unidos :D !")


Fimalgoritmo